version: "3.6"

services:
  base:
    build:
      context: src
      target: base
    image: 'docker.pkg.github.com/datadog/dd-trace-php/framwork-ci-base'
    ulimits:
      core: 99999999999
    cap_add:
      - SYS_PTRACE
