version: "3.6"

services:
  predis:
    depends_on: ['redis', 'nginx_file_server']
    environment:
      - "REDIS_HOST=redis"
      - "MEMCACHED_HOST=memcached"
    build:
      context: src
      target: predis
    image: 'docker.pkg.github.com/datadog/dd-trace-php/framwork-ci-predis:1.1'
    ulimits:
      core: 99999999999
    cap_add:
      - SYS_PTRACE

  redis:
    image: redis:5.0.5
    expose:
      - 6379

  nginx_file_server:
    build: nginx_file_server
    expose: ["80"]
