version: "2.1"

jobs:
  say_hi:
    docker:
      - image: circleci/php:7.2-cli
    steps:
      - run:
          name: "echoing a greeting"
          command: echo hi

workflows:
  version: 2
  wf1:
    jobs:
      - say_hi
